package io.github.onreg.feature.game.details.impl.test

internal object GameDetailsPaneTestTags {
    const val GAME_DETAILS_CONTENT: String = "GAME_DETAILS_CONTENT"
    const val GAME_DETAILS_LOADING: String = "GAME_DETAILS_LOADING"
    const val GAME_DETAILS_ERROR: String = "GAME_DETAILS_ERROR"
    const val GAME_DETAILS_COMPANIES_SECTION: String = "GAME_DETAILS_COMPANIES_SECTION"
    const val GAME_DETAILS_SCREENSHOTS_SECTION: String = "GAME_DETAILS_SCREENSHOTS_SECTION"
    const val GAME_DETAILS_MOVIES_SECTION: String = "GAME_DETAILS_MOVIES_SECTION"
    const val GAME_DETAILS_SERIES_SECTION: String = "GAME_DETAILS_SERIES_SECTION"
    const val GAME_DETAILS_SCREENSHOT_PREFIX: String = "GAME_DETAILS_SCREENSHOT_"
    const val GAME_DETAILS_MOVIE_PREFIX: String = "GAME_DETAILS_MOVIE_"
    const val GAME_DETAILS_SERIES_PREFIX: String = "GAME_DETAILS_SERIES_"
}
